name: Casino API Regression Test
on:
  push:
    branches: [ main ]

  workflow_dispatch:
    inputs:
      ALLURE_JOB_RUN_ID:
        description: "ALLURE_JOB_RUN_ID service parameter. Leave blank"
        required: false
      ALLURE_USERNAME:
        description: "ALLURE_USERNAME service parameter. Leave blank"
        required: false

env:
 ALLURE_RESULTS: allure-results
 ALLURE_JOB_RUN_ID: ${{ github.event.inputs.ALLURE_JOB_RUN_ID }}
 ALLURE_USERNAME: ${{ github.event.inputs.ALLURE_USERNAME }}

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Newman
      run: npm install newman
    - name: Install Allure Reporter for Newman
      run: npm install newman-reporter-allure
    - uses: allure-framework/setup-allurectl@v1
      with: 
        allure-endpoint: https://lawo.testops.cloud
        allure-token: ${{ secrets.ALLURE_TOKEN }}
        allure-project-id: 1
    - name: Run Newman with Allure
      run: |
        allurectl watch -- \
          newman run "https://api.getpostman.com/collections/12435063-f646f5d8-c666-43d6-8141-181a3fc5a552?apikey=${{ secrets.ALLURE_POSTMAN }}" \
          -r cli,allure \
          --reporter-allure-export $ALLURE_RESULTS

      #env: 
       # ALLURE_RESULTS: allure-results



        